### ISSUE TITLE
Typo in --weights-path specification

### ISSUE THREAD

**Issue by pearu** [pytorch-labs/superblock#12]
https://github.com/pytorch-labs/superblock/blob/7db1048c04815123336e06f1d1ed6ae81c67ff67/README.md?plain=1#L188

should read

```
--weights-path ./checkpoints/sp${SPARSITY}-ts${BLOCK_SIZE}.pth \ 
```

**Comment by mostafaelhoushi** [comment]
Thanks @pearu for catching this! Fixed it in this PR: https://github.com/pytorch-labs/superblock/pull/13
